### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SOF3** [superbobby2000/SocialSpy#3]
Main::$SocialSpy will keep on increasing if the user does not disable it before quitting.

**Comment by superbobby2000** [comment]
you're talking about my array? I made it so the players don't have to execute the command again after rejoining the server

**Comment by SOF3** [comment]
but it is not persistent.

**Comment by superbobby2000** [comment]
it is https://streamable.com/ulzs74

**Comment by SOF3** [comment]
It is not persistent over server restart. So this is an inconsistent feature anyway. Furthermore, you should not store all player data in memory. Use a database for that.

**Comment by superbobby2000** [comment]
fixed ig 6a7f9e3cb0865e3f3fc0691af01cb9ef0fc3897c 
why should I use a db only to store who have socialspy enabled? I'm not storing a lot of data I'm only storing their name. I also shouldn't get more than 10 entries unless for some reasons someone give the perm to everyone playing on his server

**Comment by SOF3** [comment]
Doing this in onDisable is pointless, because the memory is freed after shutdown anyway. The problem is with increasing number of players.
As for limiting to 10 entries, do you want one of the admins to be able to cause your server to crash from memory failure arbitrarily? If you don't want to, don't make assumptions that there are only 10 entries.

**Comment by superbobby2000** [comment]
I'm not limiting it I'm just telling that it's useless to make a db in that case

**Comment by SOF3** [comment]
Database refers to anything that can save data, not necessarily SQL.

**Comment by superbobby2000** [comment]
ill just fix it

**Comment by superbobby2000** [comment]
571ea9301f62fcd2e0a6290aeccc8175f005af0d
